import type { Bean, Recipe } from '@/types/brew';

export const beans: Bean[] = [
  {
    id: 'ethiopia-mist-valley',
    name: 'Mist Valley Gesha Lot 12',
    origin: 'Ethiopia',
    region: 'Yirgacheffe Highlands',
    process: 'Washed',
    roast: 'Light',
    tastingNotes: ['jasmine', 'bergamot', 'white peach'],
  },
  {
    id: 'colombia-solar-honey',
    name: 'Solar Honey Pink Bourbon',
    origin: 'Colombia',
    region: 'Huila',
    process: 'Honey',
    roast: 'Light',
    tastingNotes: ['apricot', 'raw sugar', 'orange blossom'],
  },
  {
    id: 'panama-cloud-natural',
    name: 'Cloud Estate Natural Gesha',
    origin: 'Panama',
    region: 'Boquete',
    process: 'Natural',
    roast: 'Light',
    tastingNotes: ['strawberry', 'cacao nib', 'rose'],
  },
  {
    id: 'kenya-red-volcano',
    name: 'Red Volcano SL28',
    origin: 'Kenya',
    region: 'Nyeri',
    process: 'Washed',
    roast: 'Medium',
    tastingNotes: ['blackcurrant', 'grapefruit', 'molasses'],
  },
];

const disclaimer = 'Fictional champion-style placeholder recipe for MVP use. Replace only with sourced or licensed champion recipe data.';

export const recipes: Recipe[] = [
  {
    id: 'aurora-pulse',
    slug: 'aurora-pulse',
    name: 'Aurora Pulse Pour Over',
    champion: { id: 'mira-lane', name: 'Mira Lane', competition: 'Imaginary Brewers Cup 2026', disclaimer },
    bean: beans[0],
    dose: 18,
    water: 300,
    temperature: 94,
    grind: 'Medium-fine, 720 micron target',
    targetTime: 180,
    equipment: ['V60-style dripper', 'Paper filter', 'Gooseneck kettle', 'Precision scale', 'Server'],
    overview: 'A luminous, staged pour structure designed to emphasize florals, citrus lift, and silky sweetness.',
    steps: [
      { id: 'bloom', time: 0, label: 'Bloom', instruction: 'Pour to 45g, saturating all grounds. Swirl gently once.', targetWeight: 45 },
      { id: 'first-pulse', time: 35, label: 'First pulse', instruction: 'Pour in a tight spiral to 120g, keeping the bed low and even.', targetWeight: 120 },
      { id: 'second-pulse', time: 75, label: 'Second pulse', instruction: 'Pour to 210g with a wider spiral, then pause for drawdown.', targetWeight: 210 },
      { id: 'finish', time: 120, label: 'Finish', instruction: 'Finish at 300g and let the slurry drain cleanly.', targetWeight: 300 },
    ],
    curve: [
      { time: 0, weight: 0 },
      { time: 12, weight: 45 },
      { time: 35, weight: 45 },
      { time: 55, weight: 120 },
      { time: 75, weight: 120 },
      { time: 98, weight: 210 },
      { time: 120, weight: 210 },
      { time: 145, weight: 300 },
      { time: 180, weight: 300 },
    ],
  },
  {
    id: 'citrus-arc',
    slug: 'citrus-arc',
    name: 'Citrus Arc Championship Style',
    champion: { id: 'noah-vale', name: 'Noah Vale', competition: 'Fictional World Filter Final 2025', disclaimer },
    bean: beans[1],
    dose: 20,
    water: 320,
    temperature: 92,
    grind: 'Medium, unimodal-friendly',
    targetTime: 210,
    equipment: ['Flat-bottom brewer', 'Wave filter', 'Thermal carafe', 'Precision scale'],
    overview: 'A sweet honey-process profile with longer pauses for clarity and a plush orange-blossom finish.',
    steps: [
      { id: 'open', time: 0, label: 'Open bloom', instruction: 'Pour to 60g and excavate dry pockets with a light spin.', targetWeight: 60 },
      { id: 'lift', time: 45, label: 'Sweetness lift', instruction: 'Pour to 160g, prioritizing center agitation.', targetWeight: 160 },
      { id: 'balance', time: 95, label: 'Balance pour', instruction: 'Pour to 250g and keep the kettle low.', targetWeight: 250 },
      { id: 'cap', time: 145, label: 'Final cap', instruction: 'Pour to 320g and allow a slow, even finish.', targetWeight: 320 },
    ],
    curve: [
      { time: 0, weight: 0 },
      { time: 15, weight: 60 },
      { time: 45, weight: 60 },
      { time: 70, weight: 160 },
      { time: 95, weight: 160 },
      { time: 120, weight: 250 },
      { time: 145, weight: 250 },
      { time: 175, weight: 320 },
      { time: 210, weight: 320 },
    ],
  },
  {
    id: 'velvet-bloom',
    slug: 'velvet-bloom',
    name: 'Velvet Bloom Gesha',
    champion: { id: 'sana-reyes', name: 'Sana Reyes', competition: 'Placeholder Masters Brew 2026', disclaimer },
    bean: beans[2],
    dose: 16,
    water: 260,
    temperature: 90,
    grind: 'Medium-coarse for aromatic naturals',
    targetTime: 195,
    equipment: ['Conical dripper', 'Abaca paper', 'Temperature-controlled kettle', 'Scale'],
    overview: 'A gentler low-temperature pattern intended to showcase fruit aromatics while protecting clarity.',
    steps: [
      { id: 'soft-bloom', time: 0, label: 'Soft bloom', instruction: 'Pour 40g with minimal agitation.', targetWeight: 40 },
      { id: 'fruit-pulse', time: 40, label: 'Fruit pulse', instruction: 'Pour to 110g in small circles.', targetWeight: 110 },
      { id: 'texture', time: 85, label: 'Texture pour', instruction: 'Pour to 190g, then give one gentle swirl.', targetWeight: 190 },
      { id: 'close', time: 130, label: 'Close', instruction: 'Finish at 260g and avoid late agitation.', targetWeight: 260 },
    ],
    curve: [
      { time: 0, weight: 0 },
      { time: 14, weight: 40 },
      { time: 40, weight: 40 },
      { time: 62, weight: 110 },
      { time: 85, weight: 110 },
      { time: 112, weight: 190 },
      { time: 130, weight: 190 },
      { time: 158, weight: 260 },
      { time: 195, weight: 260 },
    ],
  },
  {
    id: 'volcanic-clarity',
    slug: 'volcanic-clarity',
    name: 'Volcanic Clarity',
    champion: { id: 'eli-kamau', name: 'Eli Kamau', competition: 'Fictional National Brewers Showcase', disclaimer },
    bean: beans[3],
    dose: 19,
    water: 310,
    temperature: 95,
    grind: 'Medium-fine with fast drawdown',
    targetTime: 185,
    equipment: ['V60-style dripper', 'Rinsed paper filter', 'Gooseneck kettle', 'Scale'],
    overview: 'A bright, high-energy approach for Kenyan acidity, using assertive pulses and a clean finish.',
    steps: [
      { id: 'bloom', time: 0, label: 'Bloom', instruction: 'Pour to 55g and swirl firmly.', targetWeight: 55 },
      { id: 'drive', time: 30, label: 'Drive acidity', instruction: 'Pour to 150g with a controlled center stream.', targetWeight: 150 },
      { id: 'sweeten', time: 70, label: 'Sweeten', instruction: 'Pour to 240g, widening the spiral near the edge.', targetWeight: 240 },
      { id: 'finish', time: 115, label: 'Finish', instruction: 'Top to 310g and tap the brewer once.', targetWeight: 310 },
    ],
    curve: [
      { time: 0, weight: 0 },
      { time: 11, weight: 55 },
      { time: 30, weight: 55 },
      { time: 54, weight: 150 },
      { time: 70, weight: 150 },
      { time: 95, weight: 240 },
      { time: 115, weight: 240 },
      { time: 140, weight: 310 },
      { time: 185, weight: 310 },
    ],
  },
];

export function getRecipeBySlug(slug: string) {
  return recipes.find((recipe) => recipe.slug === slug);
}
